version: '3.8'

services:
  node_server:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5000:5000"
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - mynetwork

  python_server:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5001:5001"
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - mynetwork

networks:
  mynetwork: