# Usando a imagem oficial do Apache
FROM httpd:2.4

# Copiar seus arquivos HTML para o diretório padrão do Apache
COPY ./public-html/ /usr/local/apache2/htdocs/

# Expor a porta 80 (porta padrão do HTTP)
EXPOSE 80